export type Ticket = {
  id: number;
  subject: string;
  description: string;
  location: string;
  phoneNumber: string;
  status: string;
  type: string;
  fullName: string;
  latLng: string;
  isAnonymous: boolean;
  manager: string;
  addressNumber: string;
  addressMoo: string;
  addressRoad: string;
  addressSubDistrict: string;
  addressDistrict: string;
  addressProvince: string;
  addressZipCode: string;
  date: string;
  time: string;
  images: any[];
  isVolunteer: boolean;
  createdAt: Date;
  updatedAt: Date;
};
