import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/auth-provider";
import { getServerSession } from "next-auth/next";

import { Toaster } from "@/components/ui/sonner";
import ErrorBoundary from "@/components/error-boundary";
import ReactQueryProvider from "@/providers/react-query-provider";
import { authOptions } from "@/configs/auth-options";

const notoSansThai = Noto_Sans_Thai({ subsets: ["latin", "thai"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className="overflow-hidden h-full">
      <body className={notoSansThai.className}>
        <ErrorBoundary>
          <ReactQueryProvider>
            <AuthProvider session={session}>{children}</AuthProvider>
          </ReactQueryProvider>
        </ErrorBoundary>
        <Toaster />
      </body>
    </html>
  );
}
